options:
  backend-base-url:
    type: string
    default:
    description: |
      The jobbergate-backend-base-url
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD
 
