options:
  backend-base-url:
    type: string
    default:
    description: |
      The jobbergate-backend-base-url
  pypi-url:
    type: string
    default:
    description: |
      PYPI URL
  pypi-username:
    type: string
    default:
    description: |
      PYPI USERNAME
  pypi-password:
    type: string
    default:
    description: |
      PYPI PASSWORD
  version:
    type: string
    default:
    description: |
      The vesion of the jobbergate-cli package to install. If blank, install latest.
  sentry-dsn:
    type: string
    default:
    description: |
      An optional URL for the Sentry DSN for capturing error events
  s3-log-bucket:
    type: string
    default:
    description: |
      The log bucket where user logs may be uploaded
  aws-access-key-id:
    type: string
    default:
    description: |
      The AWS access key ID needed for uploading user logs to S3
  aws-secret-access-key:
    type: string
    default:
    description: |
      The AWS secret access key needed for uploading user logs to S3
  auth0-domain:
    type: string
    default:
    description: |
      Domain for the general Auth0 API
  auth0-login-domain:
    type: string
    default:
    description: |
      Domain for the Auth0 API where login requests are directed.
  auth0-audience:
    type: string
    default:
    description: |
      Audience for the Auth0 issued tokens.
  auth0-client-id:
    type: string
    default:
    description: |
      The ID for the Auth0 app client to which tokens will be issued.
  auth0-client-secret:
    type: string
    default:
    description: |
      The secret key for the Auth0 app client to which tokens will be issued.
